1742557657660	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1742557793722	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1742557793723	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1742557793724	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1742557793726	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1742558393727	Sync.Service	DEBUG	User-Agent: Firefox/136.0.2-1 (Linux x86_64) FxSync/1.138.0.20250319110119.desktop
1742558393727	Sync.Service	INFO	Starting sync at 2025-03-21 13:59:53 in browser session e83OQrLDXx7S
1742558393727	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1742558393731	Sync.Status	INFO	Resetting Status.
1742558393731	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1742558393732	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1742558393732	FirefoxAccounts	DEBUG	getOAuthToken enter
1742558393734	FirefoxAccounts	TRACE	getCachedToken returning cached token
1742558393734	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1742558393734	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1742558393737	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1742558393737	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.sys.mjs :: onStopRequest :: line 478\"  data: no]"}
1742558393738	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/186972506/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1742558393738	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1742558393738	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1742558393738	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1742558393739	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=reschedule)
1742558393741	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
